spring:
  output:
    ansi:
      enabled: always
  application:
    name: auth-gateway-server
  cloud:
    gateway:
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway Filter
#            preLogger: true
#            postLogger: true
      routes:
        - id: auth-server
          uri: lb://auth-auth-server
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<path>.*),/$\{path}
        - id: user-server
          uri: lb://auth-user-server
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/api/v1/user/(?<path>.*),/$\{path}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 10010
# gateway route 노출
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true