# jwt
jwt:
  secret: supersecretkey
  tokenPrefix: Bearer
# swagger
springfox:
  documentation:
    swagger:
      use-model-v3: false
# logging
logging:
  level:
    root: info
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3234/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 1234
spring:
  application:
    name: auth-auth-server
  output:
    ansi:
      enabled: always
  # swagger
  resources:
    add-mappings: true
  # db setting
  datasource:
    url: jdbc:postgresql://localhost:5432/stove_auth
    username: koiil
    password: 1234
  # hibernate setting
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  # redis
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1